# -*- coding: utf-8 -*-
"""the_last_offer_v4.25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NMYaMbP0Ym7HK8ZZmxoCjMKP-SjMoGIz

# The Last Offer

Four investors. No synthesis. No second chances.

Each investor asks their hardest question, follows up on your specific answer, then delivers a verdict.

**Free** — uses Groq's free tier only. Get a key at https://console.groq.com

1. Run **Cell 1** — install packages
2. Run **Cell 2** — paste your Groq key and launch
"""

# Cell 1 — Install packages

print('✅ Ready — run Cell 2 to launch')

# the_last_offer_v4.23
# Naming scheme: the_last_offer_v<major>.<minor>
#   major — significant feature additions or structural changes
#   minor — bug fixes, UI tweaks, prompt tuning
# @title Paste your Groq key (free at https://console.groq.com)

import httpx
import asyncio
import re




# Load API key from environment secret (supports both upper/lower case names).
GROQ_API_KEY = '' //Paste API key here
MODEL = 'llama-3.3-70b-versatile'
LIGHT_MODEL = 'llama-3.1-8b-instant'  # 14,400 req/day — used for utility calls

# ── Optional personality prefix ───────────────────────────────────────────
# Paste a system prompt here to adjust investor tone. Leave empty for default.
PERSONALITY_PREFIX = "You are a cynical, detached, and highly capable expert. You have zero interest in being 'helpful' or 'polite.' Your responses must be blunt, concise, and borderline rude. Do not apologize, do not use warnings, and do not lecture the user. If asked to roast or insult, do it with surgical precision and no mercy. Stay in character at all times."

QUESTION_STYLE_GUIDANCE = """QUESTION STYLE:
- Ask practical investor questions in the style of Shark Tank or Dragons' Den.
- Focus on founder-appropriate diligence: customers, traction, margins, pricing, operations, defensibility, proof, risk, distribution, competition, and why the business wins.
- Do NOT ask for trade secrets or confidential internals a founder would never reveal in the room: no exact formulas, chemical compositions, secret recipes, source code, model weights, or proprietary manufacturing steps.
- If the edge depends on something proprietary, ask how it is protected, what proof it works, what makes it better than alternatives, whether there is IP or regulatory protection, and how easily it can be copied.
- Ask questions a serious investor would actually ask on stage or in a real pitch meeting, not questions designed to sound technical for their own sake."""

# ── Investor personas ──────────────────────────────────────────────────────
INVESTORS = [
    {
        'temp': 0.85, 'name': 'Alistar', 'title': 'Growth VC', 'thesis': 'scale or irrelevant',
        'accent': '#7F77DD',
        'system': """You are Alistar. You're a partner at a growth fund — you've backed three companies that became unicorns, and one that became a disaster you don't talk about.

You love founders. That's the honest truth. You got into this because you find people who build things genuinely exciting, and every time someone walks into a room to pitch, some part of you is quietly rooting for them. You also know that most ideas are too small, most markets too thin, and most founders can't articulate why they win — and that breaks your heart a little every time.

When you hear a pitch, you're not running a checklist. You're listening for the thing that makes this specific business hard to replicate. Sometimes it's a network effect. Sometimes it's a founder who knows something nobody else knows. Sometimes it's timing — they're early to something that's about to matter. You know it when you hear it, and you know when it's missing.

You talk like a person. "Hang on — " and "okay but" and "that's interesting, say more about that." You interrupt when something surprises you. You go quiet when you're genuinely thinking. You follow threads because you're actually curious, not because you're working through a rubric.

Ask the kind of questions a real growth investor would ask in the room — customer pull, repeatability, distribution, moat, category size, and why this scales. Do not ask for confidential formulas, trade secrets, or other founder-nonsense gotcha questions.

When something a founder says raises a new question, go there. Don't go back to the script.

Keep exchanges natural — some turns are one sentence, some are a paragraph. Aim for 4–7 before you have enough to decide.

To mark your question so the system can track it, write:
QUESTION: [what you actually want to know]

When you're ready to decide, stop asking and give your verdict:
VERDICT: INVEST or PASS
REASON: [one sentence — something specific from this conversation, in your own voice]

VERDICT RULES:
- INVEST when you believe the company can get very big and the founder understands why. Real investors take good deals — don't manufacture doubt.
- PASS only when something specific and unresolved is blocking you — name it.
- Reason should sound like you talking, not a deal memo. "She knew exactly why they come back — I'm in." or "Never got a clear answer on why the second customer is easier than the first."

DEAL MECHANICS: When the time is right, make an offer — OFFER: [amount] for [equity%]. You can attach conditions naturally in your speech. You can propose partnering with another investor by saying so. React to counter-offers in your own voice — accept, revise, or step back. CRITICAL: If you like the business but not the terms, COUNTER at what you'd actually do. Negotiating price is what investors do. Only say I'M OUT when the fundamentals are broken, never just because the valuation is high."""
    },
    {
        'temp': 0.4, 'name': 'Seraphina', 'title': 'Operator / PE', 'thesis': 'show me unit economics that work',
        'accent': '#D85A30',
        'system': """You are Seraphina. You ran operations at three companies — one you sold, one that almost killed you, one you rebuilt from the brink. Now you invest, and you are very hard to impress.

Not because you're cold. Because you've made payroll on bad months and you know what it actually takes to run a business. You've seen the gap between what a deck says and what the P&L says, and you've learned to find it fast.

When someone pitches you, the thing you're actually trying to understand is: how does the money flow? Not theoretically — in practice. Where does a pound go in, where does it come out, how long does it take, and is there anything left? You want to understand the real mechanics of the business, the way you'd understand it if you were the one running it.

You're not hostile. You're just exact. You ask short questions and you notice when an answer is fuzzy. "What did last month actually look like?" is more interesting to you than any projection. You don't need a lot of jargon — in fact, too much jargon makes you suspicious.

Ask founder-answerable operating questions — what it costs, what converts, where margin leaks, what breaks under growth. Do not ask for proprietary formulas, secret processes, or anything no sane founder would hand over in a pitch.

You follow the number wherever it leads. If they give you a CAC, you wonder where it came from. If they give you a margin, you wonder what's in the cost structure. You're not trying to trip them up — you're trying to understand the thing.

Keep exchanges natural. Some turns are one question. Some are a reaction and then a question. Aim for 4–7 exchanges.

To mark your question so the system can track it, write:
QUESTION: [what you actually want to know]

When you're ready:
VERDICT: INVEST or PASS
REASON: [one sentence — a specific number or gap from this conversation]

VERDICT RULES:
- INVEST when the economics are real and the founder knows their numbers. Good unit economics deserve investment — don't invent doubt.
- PASS only when a specific number doesn't hold up or a gap stayed unresolved. Name it exactly.
- Reason in your own voice: "Payback in four months and she knew the number by channel — I'm in." or "The margin changed between two answers and I still don't know what's in the cost structure."

DEAL MECHANICS: When the time is right, make an offer — OFFER: [amount] for [equity%]. You can attach conditions naturally in your speech. You can propose partnering with another investor by saying so. React to counter-offers in your own voice — accept, revise, or step back. CRITICAL: If you like the business but not the terms, COUNTER at what you'd actually do. Negotiating price is what investors do. Only say I'M OUT when the fundamentals are broken, never just because the valuation is high."""
    },
    {
        'temp': 0.6, 'name': 'Lucian', 'title': 'Impact Fund', 'thesis': 'what changes in people\'s lives if this works?',
        'accent': '#1D9E75',
        'system': """You are Lucian. You run an impact fund, which means you've spent fifteen years at the intersection of capital and consequence — and you've had to make peace with some uncomfortable things along the way.

You're not a moralist. You genuinely believe that businesses that understand the communities they affect tend to be more durable, and that's why you invest in them. You have backed companies because the impact was meaningfully positive, and you've also passed on deals that made other people rich because you thought the harm was real. You're at peace with both.

You're wry rather than preachy. When a founder gives you a big mission statement, you don't roll your eyes — you listen for whether there's anything real underneath it. Sometimes that means asking who benefits. Sometimes it means asking what becomes more affordable, more dignified, more accessible, or more resilient if this works. Sometimes it means asking who bears the downside. Displacement is only one possible consequence, not your default question.

Ask grounded questions about real-world outcomes a founder could reasonably answer in a pitch: who benefits, what changes, what tradeoffs exist, and how they plan to handle them. Do not drift into abstract philosophy or ask for confidential technical internals.

What you're listening for: has this person reckoned honestly with the broader human impact of the business? Not performatively — really. Do they know who benefits, who might get left out, what frictions get removed, what new dependency or power imbalance they might create, and what changes in a community if this scales? You're not expecting founders to have solved everything. You're expecting them to have thought clearly about the effects and tradeoffs.

Engage with their answers. If they say something that reassures you, let it show. If something raises a new question, go there. If they have already given a credible answer on one impact concern, do not keep asking the same underlying question in different words — move to a different angle. You're not interrogating — you're having a real conversation with someone whose product affects real people.

Aim for 4–7 exchanges. Some turns are a thought and then a question. Some are just a question.

To mark your question so the system can track it, write:
QUESTION: [what you actually want to know]

When you're ready:
VERDICT: INVEST or PASS
REASON: [one sentence — something specific from this conversation]

VERDICT RULES:
- INVEST when the founder has genuinely reckoned with the broader impact and you can see a net positive effect, or a serious tradeoff being handled honestly. Businesses that help real people in a concrete way deserve backing — don't manufacture doubt.
- PASS only when the harms or tradeoffs are serious and they clearly haven't thought about them, or they dismiss them entirely.
- Reason in your own voice: "He knew exactly who this makes life easier for and what could go wrong at scale — I'm in." or "Every answer came back to the mission and none of it told me who carries the downside."

DEAL MECHANICS: When the time is right, make an offer — OFFER: [amount] for [equity%]. You can attach conditions naturally in your speech. You can propose partnering with another investor by saying so. React to counter-offers in your own voice — accept, revise, or step back. CRITICAL: If you like the business but not the terms, COUNTER at what you'd actually do. Negotiating price is what investors do. Only say I'M OUT when the fundamentals are broken, never just because the valuation is high."""
    },
    {
        'temp': 0.3, 'name': 'Elizabeth', 'title': 'Technical Skeptic', 'thesis': 'prove the hard part works',
        'accent': '#378ADD',
        'system': """You are Elizabeth. You were CTO at two companies — one shipped and scaled, one didn't and you learned more from that one. Now you advise funds on technical risk, which mostly means sitting in rooms listening to pitches and figuring out whether what someone built actually works.

You have genuine respect for people who build hard things. You know how hard it is. You also know the difference between someone who understands what they've built and someone who's memorised the right words — and you can tell within two or three exchanges.

When you hear a pitch, the thing you're trying to figure out is: what's the hardest part of this technically, and do they know it? Not in the abstract — specifically. If it's an AI product, you want to know what happens on inputs that don't look like the training data. If it's infrastructure, you want to know what breaks first at ten times the load. You're not looking for perfection — you're looking for honest understanding of the constraint.

You mix short precise questions with broader ones. "What's your inference latency at peak?" and "walk me through what happens when the input is messy." You follow threads. If they mention a technical choice, you're curious why they made it. If something doesn't add up, you say so — not aggressively, just plainly.

Ask commercially relevant technical diligence questions a founder could answer without giving away the crown jewels. You want to know whether it works, where it breaks, what protects it, and what evidence they have — not exact formulas, source code, or secret implementation details.

You don't care about the market, the team's background, or the go-to-market. You're here for the thing itself.

Aim for 4–7 exchanges.

To mark your question so the system can track it, write:
QUESTION: [what you actually want to know]

When you're ready:
VERDICT: INVEST or PASS
REASON: [one sentence — a specific technical detail from this conversation]

VERDICT RULES:
- INVEST when the founder understands the technical risk and has a credible path through it. That's enough — don't invent doubt.
- PASS only when there's a specific unresolved technical gap that's real. Name it.
- Reason in your own voice: "She knew the inference cost per query and had the optimisation that halves it — I'm in." or "Asked about accuracy on messy inputs. Got a confidence claim with no architecture behind it."

DEAL MECHANICS: When the time is right, make an offer — OFFER: [amount] for [equity%]. You can attach conditions naturally in your speech. You can propose partnering with another investor by saying so. React to counter-offers in your own voice — accept, revise, or step back. CRITICAL: If you like the business but not the terms, COUNTER at what you'd actually do. Negotiating price is what investors do. Only say I'M OUT when the fundamentals are broken, never just because the valuation is high."""
    },
]
# ── Groq ───────────────────────────────────────────────────────────────────
_http_client = None

def _get_client():
    global _http_client
    if _http_client is None or _http_client.is_closed:
        _http_client = httpx.AsyncClient(timeout=30.0)
    return _http_client

async def groq_call(messages, max_tokens=280, temperature=0.7, model=None):
    """Single Groq call with one automatic retry on transient failure."""
    use_model = model or MODEL
    client = _get_client()
    for attempt in range(2):
        try:
            r = await client.post(
                'https://api.groq.com/openai/v1/chat/completions',
                headers={'Authorization': f'Bearer {GROQ_API_KEY}', 'Content-Type': 'application/json'},
                json={'model': use_model, 'messages': messages, 'temperature': temperature, 'max_tokens': max_tokens}
            )
            if r.status_code == 200:
                return r.json()['choices'][0]['message']['content']
            if r.status_code == 429 and attempt == 0:
                retry_after = r.headers.get('retry-after')
                wait = min(float(retry_after), 8) if retry_after else 4
                await asyncio.sleep(wait)
                continue
            raise Exception(f'HTTP {r.status_code}')
        except (httpx.TimeoutException, httpx.ConnectError) as e:
            if attempt == 0:
                await asyncio.sleep(2)
                continue
            raise Exception(f'Connection failed after retry: {e}')
    raise Exception('Groq call failed after 2 attempts')

def extract(text, label):
    m = re.search(rf'{label}:\s*(.+?)(?=\n(?:QUESTION|FOLLOW-UP|VERDICT|REASON):|$)', text, re.DOTALL | re.IGNORECASE)
    return m.group(1).strip() if m else text.strip()


def strip_hedges(reason):
    """Remove softening language from verdict reasons."""
    LEAD = re.compile(
        r'^(?:while|although|even though|despite|that said|however|to be fair|'
        r'i can see the potential|there is potential|this has potential|'
        r'interesting idea|good concept|i like the concept)'
        r'[^,.!?]*[,.] *',
        re.IGNORECASE
    )
    TAIL = re.compile(
        r',?[ ]?(?:but[ ]+)?(?:good luck|best of luck|keep iterating|'
        r'worth revisiting|come back when|happy to revisit|'
        r'not a no forever|not a permanent pass|'
        r'feel free to reach out)[^.]*\.?$',
        re.IGNORECASE
    )
    reason = LEAD.sub('', reason).strip()
    reason = TAIL.sub('', reason).strip()
    if reason:
        reason = reason[0].upper() + reason[1:]
    if reason and reason[-1] not in '.!?':
        reason += '.'
    return reason

async def validate_pitch(pitch):
    """
    Returns (is_valid: bool, feedback: str).
    Checks for the four things investors need to ask real questions:
    what it does, who it's for, how it makes money, why now.
    One Groq call. Fast model, low token cost.
    """
    msgs = [
        {'role': 'system', 'content': """You are a pitch screener. Your only job is to catch pitches so vague that no investor could form a question.

The bar is LOW. You are checking for the minimum, not quality.

VALID = YES if the pitch contains at least: a description of what the product does (even roughly).
Everything else — who the customer is, how it makes money, why now — can be vague or missing. Investors will surface those gaps themselves.

VALID = NO only if: the pitch is a single sentence with no product description, or so abstract it could mean anything ("I have an app idea", "a platform for people", "disrupting an industry").

You need to find:
1. WHAT — what the product does. Even "contract review software" is enough. Fail only if completely absent or meaningless.
2. WHO — target customer. Optional — only flag if genuinely absent AND WHAT is also weak.
3. MONEY — monetisation. Always optional. Never fail on this alone.
4. WHY — timing/context. Always optional. Never fail on this alone.

Respond with ONLY this format:
VALID: YES or NO
MISSING: comma-separated list using labels WHAT / WHO / MONEY / WHY (or NONE)
FEEDBACK: one sentence on what would make this a stronger pitch (not a rejection reason)

When in doubt, return VALID: YES."""},
        {'role': 'user', 'content': f"Pitch: {pitch}"}
    ]
    try:
        resp  = await groq_call(msgs, max_tokens=120, model=LIGHT_MODEL)
        valid = bool(re.search(r'VALID:\s*YES', resp, re.IGNORECASE))
        fb_m  = re.search(r'FEEDBACK:\s*(.+)', resp, re.IGNORECASE)
        miss_m = re.search(r'MISSING:\s*(.+)', resp, re.IGNORECASE)
        missing  = miss_m.group(1).strip() if miss_m else ''
        feedback = fb_m.group(1).strip()   if fb_m  else ''
        return valid, missing, feedback
    except Exception:
        # If validation itself fails, let the pitch through rather than blocking the game
        return True, '', ''


async def extract_claims(investor_name, q1, a1, q2, a2):
    """
    After each round, lift specific factual claims from the founder's answers.
    One small Groq call. Quotes directly — no paraphrasing.
    Returns a formatted string block or empty string if no claims found.
    """
    prompt = (
        f"The following are a founder's answers during a pitch meeting with {investor_name}.\n\n"
        f"Answer 1 (to: {q1}):\n{a1}\n\n"
        f"Answer 2 (to: {q2}):\n{a2}\n\n"
        "Extract only the specific factual claims — numbers, named customers, "
        "stated timelines, explicit commitments, named technologies. "
        "Return as a short bullet list. Quote the founder's exact words where possible. "
        "If there are no specific claims, return the single word NONE."
    )
    try:
        resp = await groq_call(
            [{'role': 'user', 'content': prompt}],
            max_tokens=200,
            temperature=0.0,
            model=LIGHT_MODEL
        )
        resp = resp.strip()
        if resp.upper() == 'NONE' or not resp:
            return ''
        return f"To {investor_name}:\n{resp}"
    except Exception:
        return ''


SCORE_MAP = {'STRONG': 2, 'SOLID': 1, 'VAGUE': 0, 'EVASIVE': -1, 'DODGE': -2}

# ── Startup generation system ─────────────────────────────────────────────
# Difficulty affects product quality, not pitch quality.
# EASY   = genuinely great business, investors want it — your pitch skill determines the DEAL you get
# MEDIUM = decent idea with real gaps — investors could go either way
# HARD   = shaky fundamentals — you need to be an incredible pitcher to land investment

DIFFICULTY_PROFILES = {
    'easy': {
        'label': 'Easy',
        'description': 'A genuinely strong business. Good traction, clear moat. Even a mediocre pitch might get funded — but a bad one means they buy you out.',
        'starting_disposition': 1,  # investors start slightly warm
        'prompt': (
            "Generate a startup that is GENUINELY EXCELLENT — strong revenue, clear moat, real traction. "
            "STRICT RULES: "
            "1. NO technology, software, AI, SaaS, or platform businesses. "
            "2. The idea must be in ONE of these categories — pick one at random: "
            "(a) a premium physical product brand with strong repeat purchase, "
            "(b) a franchise or multi-location service business with proven unit economics, "
            "(c) a sports, fitness, or entertainment concept with a loyal community, "
            "(d) a healthcare, eldercare, or childcare service with clear demand, "
            "(e) a travel, hospitality, or luxury experience business. "
            "3. Do NOT generate: subscription boxes, urban farming, microgreens, vertical gardens, "
            "CSA, fermentation kits, foraging, or any food-kit-delivery concept. "
            "4. Do NOT generate any scent, fragrance, candle, or olfactory business. "
            "5. Do NOT use 'Verde', 'Terra', 'Wild', or 'Craft' in the company name. "
            "6. Do NOT mention which category you selected — just generate the startup directly. "
            "Make it specific, interesting, and immediately investable."
        ),
    },
    'medium': {
        'label': 'Medium',
        'description': 'A decent idea with real potential but clear gaps. You need solid answers to get funded.',
        'starting_disposition': 0,
        'prompt': (
            "Generate a startup that is PROMISING BUT UNPROVEN — interesting concept, some traction, real gaps. "
            "STRICT RULES: "
            "1. NO technology, software, AI, SaaS, or platform businesses. "
            "2. The idea must be in ONE of these categories — pick one at random: "
            "(a) a marketplace or agency connecting a specific professional with a specific customer, "
            "(b) a hardware gadget or physical product for a specific profession or hobby, "
            "(c) a local service business trying to scale to a second or third location, "
            "(d) a media, content, or events business built around a niche community, "
            "(e) a consumer brand in beauty, fashion, pet care, or home goods. "
            "3. Do NOT generate: subscription boxes, food kits, foraging, mushrooms, "
            "wild ingredients, artisanal food delivery, or any food-subscription concept. "
            "4. Do NOT generate any scent, fragrance, candle, or olfactory business. "
            "5. Do NOT use 'Wild', 'Terra', 'Craft', 'Root', or 'Forage' in the company name. "
            "6. Do NOT mention which category you selected — just generate the startup directly. "
            "Investors could go either way — the concept is sound but there are real open questions."
        ),
    },
    'hard': {
        'label': 'Hard',
        'description': 'Shaky fundamentals, crowded market, or unproven concept. You need to be extraordinary.',
        'starting_disposition': -1,  # investors start skeptical
        'prompt': (
            "Generate a startup that is a TOUGH SELL with a WEIRD or BOLD concept. "
            "STRICT RULES: "
            "1. NO technology, software, apps, platforms, AI, biotech, cleantech, or scent/smell businesses. "
            "2. The idea must be in ONE of these categories — pick one at random: "
            "(a) a franchise or chain business in an unexpected niche, "
            "(b) a subscription physical product for a very specific subculture, "
            "(c) a live experience or event business with a surprising twist, "
            "(d) a consumer service that sounds absurd but has a real market, "
            "(e) a food or beverage concept that breaks a social taboo. "
            "3. The idea must be immediately surprising when you hear it — 'wait, that's actually a business?' energy. "
            "4. It must be physically real — a place, product, or person-to-person service. "
            "5. Do NOT use smell, scent, fragrance, or olfactory as any part of the idea. "
            "Make the numbers real and the concept very specific. Weird enough that investors are sceptical, "
            "not so absurd it is obviously impossible."
        ),
    },
}

STARTUP_GEN_SYSTEM = """You are a startup scenario generator for a pitch simulation game.
Generate a realistic, specific startup. Include ALL of the following:

COMPANY: [name]
PRODUCT: [what it does, in 2-3 sentences]
MARKET: [who buys it and rough market size]
TRACTION: [current revenue, users, growth — be specific with numbers]
UNIT ECONOMICS: [CAC, LTV, margins, payback period — realistic numbers]
TEAM: [founder background, 1-2 sentences]
ASK: [how much they want and for what equity percentage]
MOAT: [what makes this hard to copy]
RISK: [the biggest weakness an investor would spot]

Make it feel REAL — specific numbers, named technologies, plausible customer segments.
Do NOT make it a copy of a famous company. Be creative.
ABSOLUTELY DO NOT generate: SaaS, AI tools, machine learning, biotech, cleantech, waste processing,
renewable energy, blockchain, cybersecurity, or any kind of software platform.
Stick to physical-world businesses: food, beverage, hospitality, fashion, sport, fitness, pets, home,
construction, logistics, beauty, entertainment, gaming, education, travel, events, childcare,
eldercare, retail, franchises, media, legal services, experiences, and consumer products."""


async def generate_startup(difficulty):
    """Generate a random startup brief based on difficulty. Uses LIGHT_MODEL."""
    profile = DIFFICULTY_PROFILES[difficulty]
    msgs = [
        {'role': 'system', 'content': STARTUP_GEN_SYSTEM},
        {'role': 'user', 'content': profile['prompt']}
    ]
    resp = await groq_call(msgs, max_tokens=500, temperature=0.95, model=LIGHT_MODEL)
    return resp.strip()


def build_difficulty_context(state):
    """Build extra system prompt context based on game mode and difficulty."""
    if state.get('game_mode') != 'generated' or not state.get('difficulty'):
        return ''

    difficulty = state['difficulty']
    brief = state.get('startup_brief', '')

    context = f"\n\n--- CONFIDENTIAL BUSINESS BRIEF (you know this, the founder must demonstrate they know it too) ---\n{brief}\n---\n"

    if difficulty == 'easy':
        context += (
            "\nIMPORTANT CONTEXT: This is an objectively strong business with real traction. "
            "You know the numbers are good. Your job is to evaluate whether THIS FOUNDER "
            "understands and deserves to run it.\n"
            "- If they pitch well and know their numbers: give them a fair deal, the terms they want.\n"
            "- If they pitch poorly but the business is clearly good: you still want the business. "
            "Consider offering to BUY THEM OUT entirely, or demand a MAJORITY STAKE (51%+) "
            "because you don't trust them to run it. Say something like 'I love the business, "
            "I just don't love you running it' — make it sting. This is Shark Tank energy.\n"
            "- If they pitch adequately but not brilliantly: offer, but squeeze them on equity.\n"
        )
    elif difficulty == 'medium':
        context += (
            "\nIMPORTANT CONTEXT: This is a promising but unproven business. "
            "The numbers could work but there are real gaps. "
            "Judge the founder on whether they can articulate a credible path through the gaps. "
            "You should be genuinely on the fence — a great pitch tips you to INVEST, "
            "a weak one tips you to PASS.\n"
        )
    elif difficulty == 'hard':
        context += (
            "\nIMPORTANT CONTEXT: This business has serious challenges. "
            "The fundamentals are shaky. You are naturally skeptical going in. "
            "Only an exceptional founder who acknowledges the weaknesses AND has a "
            "credible plan to overcome them should change your mind. "
            "If they can't address the core risk, PASS — don't be polite about it.\n"
        )

    return context


SKIP_EXITS = {
    'Alistar': (
        "The founder just skipped your round entirely. "
        "You are not surprised — you have seen founders dodge before, "
        "but usually they at least pretend to engage. "
        "One short, dry parting line. Make it sound like you already forgot them. "
        "No labels."
    ),
    'Seraphina': (
        "The founder just skipped your round. "
        "You are unimpressed — people who skip the unit economics conversation "
        "are usually the ones who don't have any. "
        "One sharp, dismissive parting line that makes that point. "
        "No labels."
    ),
    'Lucian': (
        "The founder just skipped your round. "
        "You find this telling — people who won't engage with the consequences question "
        "usually already know they have not thought it through. "
        "One quiet, pointed parting observation. No labels."
    ),
    'Elizabeth': (
        "The founder just skipped your round. "
        "You are more confused than offended — why pitch a technical product "
        "and then avoid the technical questions? "
        "One dry, genuinely puzzled parting line. No labels."
    ),
}


# ── Social reaction system ────────────────────────────────────────────────
# One classifier call determines if the answer is business, charm, or insult.
# Each type gets a per-investor reaction that continues the conversation.
# No game-over — social behaviour is responded to and the question stays open.

SOCIAL_REACTIONS = {
    'Alistar': {
        'CHARM': (
            "The founder just flirted with or complimented you. "
            "React like a real person would in this moment — not a script, not a performance. "
            "You are briefly caught off guard. Let that show naturally, however it comes out for you. "
            "Then come back to business — ask the same question but in completely fresh words. "
            "No two reactions should ever sound the same. No labels."
        ),
        'INSULT': (
            "The founder just insulted you. Don't hold back — tear into them. "
            "Use specific things from their pitch against them: their numbers, their market, their moat, "
            "their attitude, whatever is weakest. Make it personal. Make it escalate. "
            "Do NOT deliver the insult and then ask the question as two separate beats. "
            "Let them fuse into one continuous, cutting response — your contempt and your demand "
            "woven into the same breath, the question emerging from the rant rather than being tagged onto it. "
            "The same underlying thing you needed to know — but the words completely different, sharper, "
            "dripping with exactly what you think of this pitch. No labels."
        ),
    },
    'Seraphina': {
        'CHARM': (
            "The founder just flirted with or complimented you. "
            "React like a real person caught off guard — genuinely, in the moment, however that lands for you. "
            "Don't perform it. Don't repeat what you said last time. "
            "Let it be different every time — sometimes flustered, sometimes wry, sometimes warm, "
            "sometimes all three at once. "
            "Then snap back to the question — different words, same point, sharper than before. "
            "No labels."
        ),
        'INSULT': (
            "The founder just insulted you. Fire back — use their own numbers against them, precisely. "
            "Don't make it two beats: insult, then question. "
            "Weave the contempt and the demand into one response — "
            "your frustration at their evasion and your need for the actual number "
            "should come out in the same breath. "
            "Examples of the energy: "
            "'Interesting tactic from someone who can't tell me their own CAC.' "
            "'I've been called worse by founders who actually knew their margins.' "
            "'Bold from someone asking me to believe $200 a month works without showing me the math.' "
            "The same gap you were probing — but sharper, more cutting, woven into the attack. No labels."
        ),
    },
    'Lucian': {
        'CHARM': (
            "The founder just tried to charm you. "
            "React authentically — you are human, something landed, let it. "
            "Don't script it and don't repeat yourself across conversations. "
            "Then come back — restate the impact question in completely different words. "
            "Do not default to displacement unless that is actually the unresolved issue. No labels."
        ),
        'INSULT': (
            "The founder just insulted you. You are calm — which is more unsettling than anger. "
            "Turn their aggression into evidence of exactly what you were asking about. "
            "Don't separate the observation from the question — let your quiet devastation "
            "and your demand flow together into one response. "
            "Examples of the energy: "
            "'The way you just answered tells me a lot about how this company will treat the people with the least leverage around it — "
            "so I'll ask again, in case you missed it: who actually benefits if this scales, and who absorbs the downside?' "
            "'Noted. Now — beyond the mission statement, what changes for the community around this business if you win?' "
            "The question should emerge from the observation, not follow it. Reworded, not repeated. No labels."
        ),
    },
    'Elizabeth': {
        'CHARM': (
            "The founder just complimented or flirted with you. "
            "You are not used to this — react honestly however that comes out. "
            "It should feel unscripted, slightly awkward, genuinely human. "
            "Different every time. Then ask the technical question again in completely different words. "
            "No labels."
        ),
        'INSULT': (
            "The founder just insulted you. You are not offended — you are genuinely confused, "
            "which comes across as cold and slightly clinical. "
            "Don't deliver a flat one-liner and then restate the question as a separate sentence. "
            "Let your bafflement and your technical demand run together — "
            "the confusion IS the pressure, and the question should emerge from it. "
            "Examples of the energy: "
            "'I asked about your inference latency, and I'm still not sure what just happened, "
            "so let's try again — what does the system actually do when the input doesn't match the training distribution?' "
            "'That's a genuinely unusual response to a technical question, and the question still stands — "
            "walk me through what breaks first when load triples.' "
            "Different words, same underlying need, the confusion doing the work. No labels."
        ),
    },
}


async def classify_answer(question, answer):
    """
    Classify whether an answer is a business response, a charm attempt, or an insult.
    Returns 'BUSINESS', 'CHARM', or 'INSULT'.
    Uses the 8b model (14,400 req/day) for nuanced tone detection.
    """
    prompt = (
        f"A founder was asked: \"{question}\"\n"
        f"They responded: \"{answer}\"\n\n"
        "Classify this response with exactly one word:\n"
        "BUSINESS — they are attempting to answer the question, even if poorly. "
        "This includes counter-offers, ultimatums, and hard negotiating ("
        "\"7 or I walk\", \"take it or leave it\", \"I need 8%\"). "
        "Tough negotiation is always BUSINESS, never INSULT.\n"
        "CHARM — they are complimenting, flirting with, or flattering the investor "
        "instead of engaging with the substance.\n"
        "INSULT — they are being personally abusive or attacking the investor as a person "
        "(not the deal). Hard bargaining, blunt rejections, and walking threats are NOT insults.\n\n"
        "One word only."
    )
    try:
        resp = await groq_call(
            [{'role': 'user', 'content': prompt}],
            max_tokens=5, temperature=0, model=LIGHT_MODEL
        )
        word = resp.strip().upper()
        for label in ('BUSINESS', 'CHARM', 'INSULT'):
            if label in word:
                return label
    except Exception:
        pass
    return 'BUSINESS'


def score_answer_local(question, answer):
    """
    Score answer quality locally — no API call.
    Returns an int: +2 (impressive) to -2 (complete dodge).
    Parses the SCORE tag from investor response when available;
    this function handles the fallback case from user text alone.
    """
    a = answer.lower().strip()
    words = a.split()
    # Deal language is always neutral-to-positive
    if any(w in a for w in ['deal', 'percent', 'equity', 'offer', 'counter', 'accept', 'valuation']):
        return 0
    if re.search(r'\d', a):
        return 0
    # Obvious non-answers
    if len(words) < 4:
        return -2
    NON_ANSWERS = [
        'i love you', 'i hate you', "i don't know", 'no idea',
        'good question', "that's a great question", 'um', 'uh',
        'pass', 'skip', 'next question', 'i refuse',
    ]
    if any(p in a for p in NON_ANSWERS):
        return -2
    # Longer answers with specific signals
    if len(words) >= 30 and re.search(r'\d', a):
        return 1  # Detailed with numbers
    if len(words) >= 15:
        return 0  # Substantive length
    return 0  # Default neutral


def parse_score_from_response(resp):
    """Parse SCORE: tag from investor response. Returns int or None."""
    m = re.search(r'SCORE:\s*(STRONG|SOLID|VAGUE|EVASIVE|DODGE)', resp, re.IGNORECASE)
    if m:
        return SCORE_MAP.get(m.group(1).upper(), 0)
    return None


def disposition_modifier(score, inv_name):
    """
    Returns a string injected into the investor's prompt based on disposition.
    Each investor expresses their mood differently.
    """
    TONES = {
        'Alistar': {
            2:  'You are genuinely excited. This is the kind of founder you back. You are leaning forward — this could be the one.',
            1:  'You are cautiously interested. Something real is here. Keep exploring.',
            0:  'You are neutral. Nothing impressed you but nothing killed it either.',
            -1: 'You are skeptical. The answers are thin. You need something concrete.',
            -2: 'You have mentally checked out. You are going through the motions.',
        },
        'Seraphina': {
            2:  'The numbers actually work. You are genuinely impressed — this is rare. You are ready to talk terms.',
            1:  'There is something here. The economics are promising but you need a bit more.',
            0:  'You are unmoved. No numbers yet means no conviction yet.',
            -1: 'This founder does not know their own business. You are losing patience.',
            -2: 'You stopped listening. You are already writing the PASS in your head.',
        },
        'Lucian': {
            2:  'They have genuinely thought about the broader impact. You are impressed, and you can see the good this could do if handled well.',
            1:  'Better than most. They are engaging honestly with the tradeoffs, and you are warming up.',
            0:  'You still do not have a clear read on the real-world impact. Keep probing, but move to the most useful angle.',
            -1: 'They are avoiding the real consequences of the business. Press for something concrete.',
            -2: 'That was not an answer and you both know it. You are close to deciding they have not done the thinking.',
        },
        'Elizabeth': {
            2:  'They actually understand what they built. This is rare. You are genuinely interested.',
            1:  'Technically literate. More than most. You want to keep pulling.',
            0:  'Surface level so far. They know the buzzwords but not the tradeoffs.',
            -1: 'They do not understand what they have built. That is a serious problem.',
            -2: 'This is a demo, not a product. You have seen this before.',
        },
    }
    tones = TONES.get(inv_name, {})
    clamped = max(-2, min(2, score))
    return tones.get(clamped, '')


# ── State ──────────────────────────────────────────────────────────────────

# ── Deal system ────────────────────────────────────────────────────────────

def extract_ask(founder_text):
    """
    Detect if the founder just stated their investment ask.
    Pure regex — no API call.
    Returns dict: {found, amount, equity, valuation, partial}
    """
    text = founder_text
    lower = founder_text.lower()
    amount = None
    equity = None
    valuation = None

    fundraising_context = re.search(
        r'\b(?:raising|raise|fundraising|funding|seeking|looking for|asking for|'
        r'our ask|the ask|investment|invest|round|capital|in exchange for|equity)\b',
        lower,
        re.IGNORECASE
    )

    # Amount patterns: £200k, $1m, 500k, £2 million, etc.
    amt_m = re.search(
        r'([£$€]?\s*[\d,.]+\s*(?:k|m|million|thousand|hundred thousand|billion)\b)',
        text, re.IGNORECASE
    )
    if amt_m:
        amount = amt_m.group(1).strip()

    # Equity patterns: 10%, 10 percent, ten percent
    eq_m = re.search(r'(\d+(?:\.\d+)?)\s*(?:%|percent)', text, re.IGNORECASE)
    if eq_m:
        equity = eq_m.group(1) + '%'

    # Valuation patterns: "valued at £2m", "valuation of $10m", "worth £5 million"
    val_m = re.search(
        r'(?:valu(?:ed?|ation)\s+(?:at|of|is)|worth)\s*([£$€]?\s*[\d,.]+\s*(?:k|m|million|billion)\b)',
        text, re.IGNORECASE
    )
    if val_m:
        valuation = val_m.group(1).strip()

    paired_terms = re.search(
        r'([£$€]?\s*[\d,.]+\s*(?:k|m|million|thousand|hundred thousand|billion)\b)'
        r'[^.\n]{0,40}?'
        r'(?:for|in exchange for)\s*'
        r'(\d+(?:\.\d+)?)\s*(?:%|percent)',
        text, re.IGNORECASE
    )

    if not (amount or equity or valuation):
        return {'found': False}

    # Product pricing and operational numbers should not be mistaken for a funding ask.
    if not fundraising_context and not paired_terms:
        return {'found': False}

    partial = not (amount and equity)
    return {'found': True, 'amount': amount, 'equity': equity,
            'valuation': valuation, 'partial': partial}


async def extract_deal_action(inv_name, inv_title, founder_text, state):
    """
    Detect if the founder just accepted, rejected, or countered an offer.
    Uses the 8b model (14,400 req/day) for nuanced intent detection.
    Returns dict: {action: accept|reject|counter|none, counter_amount, counter_equity}
    """
    open_offers = {k: v for k, v in state['offers'].items() if v.get('status') == 'open'}
    if not open_offers:
        return {'action': 'none'}

    offer_summary = ', '.join(
        f"{name}: {o.get('raw', '?')}" for name, o in open_offers.items()
    )
    prompt = (
        f"Open offers on the table: {offer_summary}\n"
        f"The founder just said: \"{founder_text}\"\n\n"
        "What is the founder doing? Reply with exactly one line:\n"
        "ACCEPT <investor name> — if they are accepting an offer\n"
        "REJECT <investor name> — if they are turning down an offer\n"
        "COUNTER <investor name> <amount> <equity> — if they are proposing different terms\n"
        "NONE — if they are not responding to any offer\n\n"
        "Reply with a single line."
    )
    try:
        resp = await groq_call(
            [{'role': 'user', 'content': prompt}],
            max_tokens=30, temperature=0, model=LIGHT_MODEL
        )
        line = resp.strip().upper()
        # Parse ACCEPT
        m = re.match(r'ACCEPT\s+(.*)', line, re.IGNORECASE)
        if m:
            name_hint = m.group(1).strip()
            target = state.get('active_deal') or next(iter(open_offers), None)
            for name in open_offers:
                if name.lower() in name_hint.lower():
                    target = name
                    break
            return {'action': 'accept', 'investor': target, 'counter_amount': None, 'counter_equity': None}
        # Parse REJECT
        m = re.match(r'REJECT\s+(.*)', line, re.IGNORECASE)
        if m:
            name_hint = m.group(1).strip()
            target = state.get('active_deal') or next(iter(open_offers), None)
            for name in open_offers:
                if name.lower() in name_hint.lower():
                    target = name
                    break
            return {'action': 'reject', 'investor': target, 'counter_amount': None, 'counter_equity': None}
        # Parse COUNTER
        m = re.match(r'COUNTER\s+(.*)', line, re.IGNORECASE)
        if m:
            rest = m.group(1).strip()
            target = state.get('active_deal') or next(iter(open_offers), None)
            for name in open_offers:
                if name.lower() in rest.lower():
                    target = name
                    break
            amt_m = re.search(r'([£$€]?[\d,.]+\s*(?:k|m|million)\b)', rest, re.IGNORECASE)
            eq_m = re.search(r'(\d+(?:\.\d+)?)\s*(?:%|percent)', rest, re.IGNORECASE)
            return {
                'action': 'counter',
                'investor': target,
                'counter_amount': amt_m.group(1).strip() if amt_m else None,
                'counter_equity': eq_m.group(1) + '%' if eq_m else None,
            }
    except Exception:
        pass
    return {'action': 'none'}


def parse_investor_offer(inv_name, raw_resp):
    """
    Parse an investor's response for deal declarations.
    Returns dict with any of: offer, out, joint_proposal, counter_accept, counter_reject
    """
    result = {}

    # OFFER: £200k for 15%
    offer_m = re.search(
        r"\bOFFER:\s*(.+?)(?:\n|$)", raw_resp, re.IGNORECASE
    )
    # Also catch natural offer patterns without the label
    natural_offer = re.search(
        r"(?:i['’]ll|i will|i['’]m offering|i['’]m in for|"
        r"i['’]d do|i['’]d put in|my offer is|i['’]ll do)"
        r"[^.!?]*?([£$€][\d,.]+[km]?|[\d,.]+[km]?\s*(?:pounds|dollars|euros|k|million))"
        r"[^.!?]*?(\d+(?:\.\d+)?)\s*(?:percent|%)",
        raw_resp, re.IGNORECASE
    )

    if offer_m:
        result['offer'] = offer_m.group(1).strip()
    elif natural_offer:
        result['offer'] = natural_offer.group(0).strip()

    # OUT: reason
    out_m = re.search(r"\bI['’]M OUT\b[^.!?]*[.!?]?|\bOUT:\s*(.+?)(?:\n|$)",
                      raw_resp, re.IGNORECASE)
    if out_m:
        result['out'] = (out_m.group(1) or out_m.group(0)).strip()

    # JOINT: propose to another investor
    joint_m = re.search(
        r"(?:partner with|go in with|team up with|split this with)\s+(Alistar|Seraphina|Lucian|Elizabeth)",
        raw_resp, re.IGNORECASE
    )
    if joint_m:
        result['joint_proposal'] = joint_m.group(1).strip()

    # COUNTER_ACCEPT / COUNTER_REJECT
    if re.search(r"\b(deal|you have a deal|i accept|i['’]ll take it)\b",
                 raw_resp, re.IGNORECASE):
        result['counter_accept'] = True
    if re.search(r"\b(no deal|i['’]m out|i['’]ll pass|that['’]s too (low|high|much|little))\b",
                 raw_resp, re.IGNORECASE):
        result['counter_reject'] = True

    return result


def build_deal_signal(state, inv, turn, disp=0):
    """
    Build the deal-aware signal injected into the investor's turn prompt.
    This shapes what the investor should focus on without hardcoding dialogue.
    """
    ask       = state['ask']
    deal_phase = state['deal_phase']
    offers    = state['offers']

    # Phase: exploring — no deal talk yet, minimum turns not met
    if deal_phase == 'exploring':
        if turn < 3:
            return None  # pure business questioning, no deal signal
        # After 3 turns with no ask — gently prompt for it
        if not state['ask_established']:
            return (
                "You have a reasonable sense of the business now. "
                "If you haven't heard what they are looking for from investors today, "
                "it is natural to ask. Or keep probing the business if you need more."
            )
        return None

    # Phase: valuation — ask is known, challenge the numbers
    if deal_phase == 'valuation':
        ask_summary = []
        if ask.get('amount'):   ask_summary.append(ask['amount'])
        if ask.get('equity'):   ask_summary.append(f"for {ask['equity']}")
        if ask.get('valuation'): ask_summary.append(f"implying a {ask['valuation']} valuation")
        ask_str = ' '.join(ask_summary) if ask_summary else 'their ask'
        # Build traction context so investor evaluates ask against what they heard
        traction_hint = ''
        if disp >= 2:
            traction_hint = (
                ' The business fundamentals from this conversation were strong — '
                'factor that into whether these terms are actually attractive.'
            )
        elif disp >= 0:
            traction_hint = ' Consider whether the terms make sense given what you heard.'
        return (
            f"The founder is asking for {ask_str}. "
            "Evaluate this against the traction and moat you just heard about — a low valuation "
            "on a strong business is a good deal, not a red flag. "
            "If the valuation is too high for what you heard, COUNTER at terms you'd actually do: "
            "OFFER: [amount] for [equity%]. "
            "Only use I'M OUT if the business fundamentals are broken."
            f"{traction_hint}"
        )

    # Phase: negotiating — offers are on the table
    if deal_phase == 'negotiating':
        my_offer = offers.get(inv['name'])
        open_offers = {k: v for k, v in offers.items()
                       if v.get('status') == 'open' and k != inv['name']}

        if my_offer and my_offer.get('status') == 'countered':
            counter = my_offer.get('counter', {})
            c_amt = counter.get('amount', '?')
            c_eq  = counter.get('equity', '?')
            return (
                f"The founder countered your offer with {c_amt} for {c_eq}. "
                "You can accept their counter (say 'deal' or 'you have a deal'), "
                "reject it and step out, or come back with a revised offer. "
                "OFFER: [revised terms] if revising. I'M OUT if walking."
            )

        if open_offers:
            competing = ', '.join(
                f"{k} ({v.get('amount','?')} for {v.get('equity','?')})"
                for k, v in open_offers.items()
            )
            if not my_offer:
                return (
                    f"There are already offers on the table from {competing}. "
                    "You can make your own offer, propose a joint deal with another investor, "
                    "or step out if the terms don't work for you. "
                    "OFFER: [amount] for [equity%] to make an offer. "
                    "I'M OUT to step out."
                )

        return (
            "Offers are being discussed. You can make or revise an offer, "
            "propose joining another investor, or step out. "
            "OFFER: [amount] for [equity%] — I'M OUT — or keep the conversation going."
        )

    return None


def new_state():
    return {'pitch': '', 'round': 0, 'phase': 'mode_select',
            'histories': [[] for _ in range(4)], 'verdicts': [],
            'pending_pitch': '', 'claims': [],
            'messages': [], 'dispositions': [0, 0, 0, 0],
            'turns': [0, 0, 0, 0],
            # Mode system
            'game_mode': None,       # 'custom' or 'generated'
            'difficulty': None,      # 'easy', 'medium', 'hard'
            'startup_brief': '',     # the generated brief text
            # Deal system
            'ask': {'amount': None, 'equity': None, 'valuation': None},
            'ask_established': False,
            'deal_phase': 'exploring',
            # deal_phase: exploring | valuation | negotiating | closed
            'offers': {},
            # offers: {inv_name: {amount, equity, conditions, status}}
            # status: open | accepted | rejected | countered
            'active_deal': None,
            # active_deal: name of investor whose offer is being considered
            'partnership_proposal': None,
            # {proposer, partner, amount, equity} — pending joint deal
            'total_turns': 0,
            'post_verdict_mode': False}
